/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ping;

import com.ping.service.crawl.CrawlerMachine;
import com.utils.CodeUtils;
import com.utils.OSUtil;
import java.util.Random;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author duyuno
 */
public class TestUI extends javax.swing.JFrame {

    /**
     * Creates new form TestUI
     */
//    WebDriver driver;
    CrawlerMachine alieXCrawler;
//    Image iconImage;

    public TestUI() {
        initComponents();
        OSUtil.setAppTitle(this);

        if (OSUtil.isWindows()) {
            System.setProperty("webdriver.chrome.driver", "Configs/chromedriver.exe");
        } else {
            System.setProperty("webdriver.chrome.driver", "Configs/chromedriver");
        }

//        Image image2 = icon.getImage().getScaledInstance(200,200,0);
//        DesiredCapabilities capabilities = DesiredCapabilities.chrome();
//        String chromeProfilePath = "C:\\Users\\Admin\\AppData\\Local\\Google\\Chrome\\User Data";
//        ArrayList<String> switches = new ArrayList<String>();
//        switches.add("--user-data-dir=" + chromeProfile);
//        capabilities.setCapability("chrome.switches", switches);
//        WebDriver driver = new ChromeDriver(capabilities);
//        String chromeProfilePath = "/Users/duyuno/Bitbucket/Profile";
//        ChromeOptions chromeProfile = new ChromeOptions();
//        chromeProfile.addArguments("chrome.switches", "--disable-extensions");
//        chromeProfile.addArguments("user-data-dir=" + chromeProfilePath);
//
//        driver = new ChromeDriver(chromeProfile);
//        driver.get("https://www.aliexpress.com");
//        AliexParameterFactory.initClientId();
//
//        if (alieXCrawler == null) {
//            alieXCrawler = new AlieXCrawler();
//            alieXCrawler.initDriver();
//            alieXCrawler.goToPage("https://login.aliexpress.com");
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtPrefix = new javax.swing.JTextField();
        lbResult = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Test");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPrefix, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(txtPrefix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(lbResult, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton2.setText("Get Random");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jButton2)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jButton1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(45, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(101, 101, 101))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String[] options = new String[]{"Okie", "Close"};
        
        String msg = "<html>This is how to get:<ul><li><i>italics</i> and "
        + "<li><b>bold</b> and "
        + "<li><u>underlined</u>...</ul></html>";
        JLabel label = new JLabel(msg);
        
        JOptionPane.showOptionDialog(this,
                label,
                "Alert",
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.INFORMATION_MESSAGE,
                null,
                options,
                options[0]);
        
//        JOptionPane.showMessageDialog(this, label, "Alert",
//                JOptionPane.INFORMATION_MESSAGE);
        
//        OSUtil.openFileOrFolder(Configs.TOOL_DATA_PATH);
        
//        try {
            // TODO add your handling code here:
//        System.out.println("" + driver.getCurrentUrl());
//        System.out.println("" + driver.getPageSource());
//        System.out.println("" + driver.getWindowHandle());
//        WebElement webElement = driver.findElement(By.id(id));
//        System.out.println("" + driver.findElement(by));
//        alieXCrawler.getListAliexProducts("1", "2", "3");

//        DialogUtil.showOptionsQuestionDialog(this, "QuestionDialog", "Duyuno ", "Dong y", "Huy");
//        DialogUtil.showOptionsMessageDialog(this, "MessageDialog", "Duyuno ", "Dong y", "Huy");
//        DialogUtil.showErrorMessage(this, "ErrorMessage", "Uno");
//        ProductImageUI productImageUI = new ProductImageUI(null);
//        productImageUI.setVisible(true);
//        GridLayoutDemo gridLayoutDemo = new GridLayoutDemo("GridImage");
//        gridLayoutDemo.setVisible(true);
//        gridLayoutDemo.cre
//            GridLayoutDemo.createAndShowGUI();
            

//        ImagePanel imagePanel = new ImagePanel();
//        imagePanel.setVisible(true);
//        } catch (MalformedURLException ex) {
//            Logger.getLogger(TestUI.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String prefix = txtPrefix.getText();
        int number = CodeUtils.genRandomNumberWithPrefix(prefix, new Random());
        lbResult.setText("" + number);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbResult;
    private javax.swing.JTextField txtPrefix;
    // End of variables declaration//GEN-END:variables
}
